<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MicaGo.Core.ContractTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\micaGO.Core\micaGO.Core.csproj" />
    <ProjectReference Include="..\..\src\micaGO.Infrastructure\micaGO.Infrastructure.csproj" />
  </ItemGroup>
</Project>
