using System.Globalization;

namespace MicaGo.App.Services;

public sealed class LocalizationService
{
    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Tables = new Dictionary<string, IReadOnlyDictionary<string, string>>
    {
        ["en"] = new Dictionary<string, string> { ["search"]="Search conversations", ["message"]="Message", ["settings"]="Settings", ["connection"]="Connection", ["appearance"]="Appearance", ["language"]="Language", ["notifications"]="Notifications", ["notify"]="Show new-message notifications", ["contacts"]="Contacts", ["contactsHint"]="Match message handles with Google Contacts or an existing CSV export on this PC.", ["importCsv"]="Import contacts from CSV", ["importingCsv"]="Importing contacts…", ["csvImported"]="Imported {0} contacts across {1} addresses; skipped {2} rows.", ["csvImportFailed"]="CSV import failed: {0}", ["signInGoogle"]="Sign in with Google", ["cache"]="Storage", ["clearCache"]="Clear local message and media cache", ["details"]="Conversation details", ["participants"]="Participants", ["conversation"]="Conversation", ["sharedMedia"]="Shared media", ["mute"]="Mute notifications", ["pin"]="Pin conversation", ["selectConversation"]="Select a conversation", ["chooseConversation"]="Choose a conversation to start", ["localOnly"]="Messages stay on this device", ["attach"]="Attach", ["send"]="Send", ["edit"]="Edit", ["unsend"]="Unsend", ["delete"]="Delete" },
        ["zh-Hans"] = new Dictionary<string, string> { ["search"]="搜索会话", ["message"]="信息", ["settings"]="设置", ["connection"]="连接", ["appearance"]="外观", ["language"]="语言", ["notifications"]="通知", ["notify"]="显示新消息通知", ["contacts"]="联系人", ["contactsHint"]="使用 Google 通讯录或这台电脑上的 CSV 导出文件匹配消息地址。", ["importCsv"]="从 CSV 导入联系人", ["importingCsv"]="正在导入联系人…", ["csvImported"]="已导入 {0} 位联系人、{1} 个地址；跳过 {2} 行。", ["csvImportFailed"]="CSV 导入失败：{0}", ["signInGoogle"]="登录 Google", ["cache"]="存储", ["clearCache"]="清除本地消息与媒体缓存", ["details"]="会话详情", ["participants"]="参与者", ["conversation"]="会话", ["sharedMedia"]="共享媒体", ["mute"]="静音通知", ["pin"]="置顶会话", ["selectConversation"]="选择一个会话", ["chooseConversation"]="选择会话以开始", ["localOnly"]="消息保留在这台设备上", ["attach"]="添加附件", ["send"]="发送", ["edit"]="编辑", ["unsend"]="撤回", ["delete"]="删除" },
        ["zh-Hant"] = new Dictionary<string, string> { ["search"]="搜尋對話", ["message"]="訊息", ["settings"]="設定", ["connection"]="連線", ["appearance"]="外觀", ["language"]="語言", ["notifications"]="通知", ["notify"]="顯示新訊息通知", ["contacts"]="聯絡人", ["contactsHint"]="使用 Google 聯絡人或這台電腦上的 CSV 匯出檔比對訊息地址。", ["importCsv"]="從 CSV 匯入聯絡人", ["importingCsv"]="正在匯入聯絡人…", ["csvImported"]="已匯入 {0} 位聯絡人、{1} 個地址；略過 {2} 列。", ["csvImportFailed"]="CSV 匯入失敗：{0}", ["signInGoogle"]="登入 Google", ["cache"]="儲存空間", ["clearCache"]="清除本機訊息與媒體快取", ["details"]="對話詳細資料", ["participants"]="參與者", ["conversation"]="對話", ["sharedMedia"]="共享媒體", ["mute"]="將通知靜音", ["pin"]="置頂對話", ["selectConversation"]="選擇一個對話", ["chooseConversation"]="選擇對話以開始", ["localOnly"]="訊息保留在這台裝置上", ["attach"]="加入附件", ["send"]="傳送", ["edit"]="編輯", ["unsend"]="收回", ["delete"]="刪除" },
    };
    public string Language { get; private set; } = ResolveSystemLanguage();
    public void SetLanguage(string value) => Language = Tables.ContainsKey(value) ? value : ResolveSystemLanguage();
    public string this[string key] => Tables.TryGetValue(Language, out var table) && table.TryGetValue(key, out var value) ? value : Tables["en"].GetValueOrDefault(key, key);
    private static string ResolveSystemLanguage() { var name = CultureInfo.CurrentUICulture.Name; return name.StartsWith("zh-Hant", StringComparison.OrdinalIgnoreCase) || name is "zh-TW" or "zh-HK" or "zh-MO" ? "zh-Hant" : name.StartsWith("zh", StringComparison.OrdinalIgnoreCase) ? "zh-Hans" : "en"; }
}
