<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <MicaGoVersion>0.87.0</MicaGoVersion>
    <Version>$(MicaGoVersion)</Version>
    <AssemblyVersion>$(MicaGoVersion).0</AssemblyVersion>
    <FileVersion>$(MicaGoVersion).0</FileVersion>
    <InformationalVersion>$(MicaGoVersion)</InformationalVersion>
  </PropertyGroup>
</Project>
